name: PR Reviewer v4

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
  pull_request_review_comment:
    types: 
      - created

jobs:
  git-diff-review:
    runs-on: ubuntu-latest
    # For pull requests: Trigger if the PR body doesn't contain '@Entelligence.AI: ignore'
    if: "!contains(github.event.pull_request.body, '@Entelligence.AI: ignore')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Git Diff Review Docker Action
        uses: docker://ghcr.io/entelligence-ai/pr_reviewer_test:v5
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          EVENT_TYPE: ${{ github.event_name }}
          ACTION_TYPE: ${{ github.event.action }}
